### ISSUE TITLE
crypto/pycrypto/pycryptodome not running cypher correctly.

### ISSUE THREAD

**Issue by gizm0d0** [bdshields/NFAuthenticationKey#2]
Hello bdshields,

I am trying to run this through python3.10 as that's what looks to be used.

However am getting the following traceback errors as soon as CTRL+D is pushed twice;

Traceback (most recent call last):
  File "/home/user/NFAuthenticationKey.py", line 102, in <module>
    cipher = AES.new(key, AES.MODE_CBC, iv)
  File "/usr/local/lib/python3.10/dist-packages/Crypto/Cipher/AES.py", line 228, in new
    return _create_cipher(sys.modules[__name__], key, mode, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/Crypto/Cipher/__init__.py", line 79, in _create_cipher
    return modes[mode](factory, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/Crypto/Cipher/_mode_cbc.py", line 274, in _create_cbc_cipher
    cipher_state = factory._create_base_cipher(kwargs)
  File "/usr/local/lib/python3.10/dist-packages/Crypto/Cipher/AES.py", line 100, in _create_base_cipher
    result = start_operation(c_uint8_ptr(key),
  File "/usr/local/lib/python3.10/dist-packages/Crypto/Util/_raw_api.py", line 242, in c_uint8_ptr
    raise TypeError("Object type %s cannot be passed to C code" % type(data))
TypeError: Object type <class 'str'> cannot be passed to C code

Any idea what could be causing this? Thanks in advance.

**Comment by ffaerian** [comment]
```
# initialise the cipher
cipher = AES.new(key.encode('utf-8'), AES.MODE_CBC, iv)

# encrypt the data
encoded = cipher.encrypt(_pad(json_data).encode('utf-8'))
```

**Comment by ffaerian** [comment]
```
def processData():
    data = {}
    cookies = []
    cookie = dict()
    data['app_name']="NFAuthenticationKey"
    data['app_version']="1.0.0.0"
    data['app_system']="Windows"
    data['app_author']="CastagnaIT"
    data['timestamp']=int(datetime.now().timestamp())+432000
    state=0
    key =""
    for line in sys.stdin:
        items = line.split('\t')
        if len(items)==1 and items[0]=='\n':
            continue
        if len(items)!=12:
            raise Exception("unexpected input:" + str(len(items)) + ", " + str(items))
        cookie["name"]=items[0]
        cookie["value"]=items[1]
        cookie["domain"]=items[2]
        cookie["path"]=items[3]
        cookie["expires"]=-1 if items[4] == "When the browsing session ends" else datetime.fromisoformat(items[4]).timestamp()
        cookie["httpOnly"]=False if items[6] == "Yes" else True  #items[5] is size
        cookie["secure"]=True if items[7] == "Secure same-site connections only" else False
        cookies.append(cookie)
        cookie = dict()
    data['data']=dict()
    data['data']['cookies']=cookies
    return data
```
really untested
